name: Deploy MERN App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Step 1: Setting up SSH keys"
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        echo "Step 1: SSH keys configured"

        echo "Step 2: Cleaning up old files on EC2"
        ssh $EC2_USER@$EC2_HOST "
          rm -rf /home/$EC2_USER/ExpenseApp-26-Nov/backend/*
          rm -rf /home/$EC2_USER/ExpenseApp-26-Nov/best-frontend/dist/*
        "
        echo "Step 2: Old files cleaned up"

        echo "Step 3: Transferring backend files to EC2"
        scp -v -r ./backend $EC2_USER@$EC2_HOST:/home/$EC2_USER/ExpenseApp-26-Nov/backend
        echo "Step 3: Backend files transferred"

        echo "Step 4: Building and transferring frontend files"
        cd best-frontend
        npm install
        npm run build
        cd ..
        scp -v -r ./best-frontend/dist $EC2_USER@$EC2_HOST:/home/$EC2_USER/ExpenseApp-26-Nov/best-frontend/dist
        echo "Step 4: Frontend files built and transferred"

        echo "Step 5: Installing backend dependencies and restarting backend service"
        ssh $EC2_USER@$EC2_HOST "
          cd /home/$EC2_USER/ExpenseApp-26-Nov/backend
          npm install --silent
          sudo systemctl restart backend.service
        "
        echo "Step 5: Backend service restarted"

        echo "Step 6: Restarting frontend service"
        ssh $EC2_USER@$EC2_HOST "
          sudo systemctl daemon-reload
          sudo systemctl restart frontend.service
        "
        echo "Step 6: Frontend service restarted"

        echo "Deployment Completed Successfully!"

