name: Deploy MERN App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Matches your Node.js version on EC2

    - name: Build Frontend
      run: |
        cd best-frontend
        npm install
        npm run build
        cd ..

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # Configure SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Transfer files to EC2
        scp -r ./backend $EC2_USER@$EC2_HOST:/home/$EC2_USER/ExpenseApp-26-Nov/backend
        scp -r ./best-frontend/dist $EC2_USER@$EC2_HOST:/home/$EC2_USER/ExpenseApp-26-Nov/best-frontend/dist

        # Install backend dependencies and restart services
        ssh $EC2_USER@$EC2_HOST "
          cd /home/$EC2_USER/ExpenseApp-26-Nov/backend
          npm install
          npm install -g nodemon
          sudo systemctl restart backend.service
          sudo systemctl restart frontend.service
        "

