name: CI/CD for MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        EC2_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Set up SSH agent and add private key
        eval "$(ssh-agent -s)"  # Start the SSH agent
        echo "$EC2_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh-add private_key.pem

        # Deploy code to EC2
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
        cd $DEPLOY_DIR || exit 1

        # Pull latest changes
        git pull origin main || exit 1

        # Backend setup
        cd backend || exit 1
        npm install --silent || exit 1

        # Frontend setup
        cd ../best-frontend || exit 1
        npm install || exit 1
        npm run build || exit 1

        # Restart services
        sudo systemctl restart backend.service || exit 1
        sudo systemctl restart frontend.service || exit 1
        "

    - name: Cleanup private key
      run: |
        rm -f private_key.pem

